9560 MainProcess 2024-03-07 10:54:10,718
Traceback (most recent call last):
  File "C:\Users\ranja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 718, in main
    main_entry(sys.argv[1:])
  File "C:\Users\ranja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 706, in main_entry
    return args.func(ctx, args)
  File "C:\Users\ranja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 236, in cmd_gen
    builder.process(options)
  File "C:\Users\ranja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyarmor\cli\generate.py", line 157, in process
    self._obfuscate_scripts()
  File "C:\Users\ranja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyarmor\cli\generate.py", line 120, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "C:\Users\ranja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyarmor\cli\core\__init__.py", line 103, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 675, in generate_obfuscated_script
  File "C:\Users\ranja\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 505, in process
  File "<maker>", line 511, in coserialize
  File "<maker>", line 556, in _build_ast_body
RuntimeError: out of license
